### ISSUE TITLE
Feature request: Disable spell check for comments

### ISSUE THREAD

**Issue by lisakmalins** [julzerinos/spellcheck-toggler-obsidian-plugin#1]
Hi! Thanks for making this plugin. Would it be possible to add a toggle to disable spell check for HTML-style comments? (For example, `<!-- this is a comment I don't want spell-checked -->`)

**Comment by julzerinos** [comment]
@lisakmalins updated with v1.1.0, though not sure what the release time is on Obsidian side. I'll keep an eye on it.

**Comment by julzerinos** [comment]
Apparently the answer is instantly :) don't forget to update!

![image](https://github.com/julzerinos/spellcheck-toggler-obsidian-plugin/assets/30495990/01c4e0e6-8d52-42a3-9edd-58e860ac9696)
