### ISSUE TITLE
Doesn't disable spellchecking on some external links

### ISSUE THREAD

**Issue by notuntoward** [julzerinos/spellcheck-toggler-obsidian-plugin#3]
Spell checking is still on for this link:  `[GitHub - alangrainger/obsidian...](https://github.com/alangrainger/obsidian-lazy-plugins)`:

![image](https://github.com/user-attachments/assets/f58baaf3-db9e-4656-a49e-2f66bd8c9cc5)

Here are my settings:

![image](https://github.com/user-attachments/assets/b204d430-c85c-485d-a8f8-59b870b2e92f)

**Comment by notuntoward** [comment]
No this does work.  Nevermind.

**Comment by julzerinos** [comment]
For future reference - sometimes the document renderer needs a refresh after toggling the settings (or installing the plugin). Usually closing the note and opening it again does the trick. 

A little annoying, but haven't looked into solving it.
